name: AdSync
main: com.ahhmino.adsync.AdSyncPlugin
version: 2.0.0
api-version: 1.16
commands:
  adsync:
    description: Global advancement synchronization
    usage: /adsync <enable|disable|reload|scan>
    permission: adsync.use
permissions:
  adsync.use:
    default: op
